# Generated by Django 3.1.2 on 2020-11-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20201108_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_file',
            field=models.FileField(null=True, upload_to='docs'),
        ),
    ]
